name: Backend Docker Build and Push

on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - "backend.Dockerfile"
      - ".github/workflows/backend-build-push.yml"
  pull_request:
    branches: [main]
    paths:
      - "api/**"
      - "backend.Dockerfile"
      - ".github/workflows/backend-build-push.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
