name: Frontend Docker Build and Push

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "public/**"
      - "package.json"
      - "package-lock.json"
      - "vite.config.ts"
      - "tsconfig*.json"
      - "frontend.Dockerfile"
      - "nginx.conf"
      - ".github/workflows/frontend-build-push.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "public/**"
      - "package.json"
      - "package-lock.json"
      - "vite.config.ts"
      - "tsconfig*.json"
      - "frontend.Dockerfile"
      - "nginx.conf"
      - ".github/workflows/frontend-build-push.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Cloud
        if: github.event_name != 'pull_request'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        if: github.event_name != 'pull_request'
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for Artifact Registry
        if: github.event_name != 'pull_request'
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push to Google Artifact Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/blog-frontend/blog-frontend:latest
          build-args: |
            VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }}
            VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }}
            VITE_AUTH0_CALLBACK_URL=${{ secrets.VITE_AUTH0_CALLBACK_URL }}
            VITE_API_URL=${{ secrets.VITE_API_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
